version: "3.8"

services:
  app:
    container_name: flask_app
    build: .
    command: gunicorn --bind 0.0.0.0:4200 app:app
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    depends_on:
      - db

  db:
    container_name: flask_db
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flask_project_db

  nginx:
    container_name: flask_nginx
    image: nginx:1.19.10-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  postgres_data:
