version: "3.8"

services:
  app:
    container_name: django_app
    build: .
    command: gunicorn --bind 0.0.0.0:8080 django_project.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    container_name: django_db
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=django_project_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  redis:
    container_name: django_redis
    image: redis:6.0.4-alpine
    volumes:
      - redis_data:/data
    expose:
      - 6379
    ports:
      - "6379:6379"

  celery_worker:
    container_name: django_celery
    build: .
    command: celery --app django_project worker
    depends_on:
      - db
      - app
      - redis

  celery_beat:
    container_name: django_celery_beat
    build: .
    command: celery --app django_project beat
    depends_on:
      - db
      - app
      - redis

  nginx:
    container_name: django_nginx
    image: nginx:1.19.10-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/staticfiles
    depends_on:
      - app

volumes:
  postgres_data:
  redis_data:
  static_volume:
